from rabbitmq:3.5.6-management
maintainer rickard@gimerstedt.se
run curl -o /usr/lib/rabbitmq/lib/rabbitmq_server-3.5.6/plugins/rabbitmq_recent_history_exchange.ez \
		http://www.rabbitmq.com/community-plugins/v3.5.x/rabbitmq_recent_history_exchange-1.2.1-rmq3.5.x-87b7ac4b.ez
run rabbitmq-plugins enable --offline rabbitmq_recent_history_exchange
